image:
  pullPolicy: IfNotPresent

ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble.127.0.0.1.nip.io

ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  service:
    insecureNodePort: 30000
    secureNodePort: 30001
    type: NodePort
