---
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: telepresence-oss
  namespace: ambassador
spec:
  interval: 10m
  url: oci://ghcr.io/telepresenceio/telepresence-oss
  ref:
    tag: latest
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: telepresence-oss
  values:
    installCRDs: true


#helm install --create-namespace --namespace ambassador traffic-manager oci://ghcr.io/telepresenceio/telepresence-oss
