---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.17.1
  interval: 1m0s
  values:
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    crds:
      enabled: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: cert-manager
spec:
  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#spec:
#  acme:
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    email: $EMAIL_ADDRESS
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    solvers:
#    - dns01:
#        azureDNS:
#          resourceGroupName: $AZURE_DEFAULTS_GROUP
#          subscriptionID: $AZURE_SUBSCRIPTION_ID
#          hostedZoneName: $DOMAIN_NAME
#          environment: AzurePublicCloud
#          managedIdentity:
#            clientID: $USER_ASSIGNED_IDENTITY_CLIENT_ID
